/**
 * ThemeSchema — value objects describing the output of the first LLM call.
 * The LLM generates objective "buckets" with fallback place types, not final legs.
 * Pure domain. No framework imports.
 */

/**
 * A candidate objective bucket generated by the LLM.
 * Each bucket specifies 1-3 Google Places types (primary + fallbacks)
 * so the system can find alternatives if the primary type has no nearby results.
 */
export interface ObjectiveBucket {
  /** Stable identifier for cross-referencing during selection. */
  readonly bucketId: string;
  /** 1-3 Google Places API types, ordered by preference. */
  readonly placeTypes: readonly string[];
  /** Short narrative hint for this objective (e.g., "acquire a signal dampener"). */
  readonly narrativeHint: string;
  /** How central this bucket is to the quest theme (0-1). */
  readonly thematicStrength: number;
}

/**
 * The theme skeleton returned by the first LLM call.
 * Contains more buckets than needed so the selection step can choose the best subset.
 */
export interface ThemeSchema {
  /** Working title for the quest (may be refined in narrative pass). */
  readonly titleSeed: string;
  /** 1-2 sentence quest premise for the narrative pass. */
  readonly narrativePremise: string;
  /** Candidate objective buckets (typically 1.5-2x objectiveCount). */
  readonly buckets: readonly ObjectiveBucket[];
}
